server_name: "pgck-local"
listen: "0.0.0.0:4222"
http: "0.0.0.0:8222"

authorization {
  users = [
    {
      user: browser_wss
      permissions = {
        publish = []
        subscribe = [$PGCK_BROWSER_NATS_SUBJECT]
      }
    }
    {
      user: $NATS_USER
      password: $NATS_PASSWORD
    }
  ]
}

websocket {
  listen: "0.0.0.0:8443"
  no_auth_user: browser_wss
  tls {
    cert_file: "/etc/nats/certs/server.pem"
    key_file: "/etc/nats/certs/server-key.pem"
  }
  same_origin: false
}
