server_name: "pgck-local"
listen: "0.0.0.0:4222"
http: "0.0.0.0:8222"

websocket {
  listen: "0.0.0.0:8443"
  tls {
    cert_file: "/etc/nats/certs/server.pem"
    key_file: "/etc/nats/certs/server-key.pem"
  }
  same_origin: false
}
