#!/usr/bin/env python3
"""Regenerate LATEST.md from current GHCR heads.

Called by `.github/workflows/update-latest-md.yml` AFTER provenance attestation
verification succeeds. Refuses to write a head whose digest doesn't match the
GHCR API answer for the verified tag.

Inputs (env):
  EXT_VER  e.g. ``0.1.7``                     — extension version (no ``v`` prefix)
  WEB_VER  e.g. ``v0.2.3``                    — pgck-web tag (with ``v`` prefix)
  GH_TOKEN  GitHub token with ``packages:read`` — passed to ``gh api``

Output: full LATEST.md content on stdout.
"""

from __future__ import annotations

import datetime
import json
import os
import subprocess
import sys
from typing import Tuple


def gh_api(path: str) -> list[dict]:
    """Call ``gh api <path> --paginate`` and return parsed JSON."""
    r = subprocess.run(
        ["gh", "api", path, "--paginate"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(r.stdout)


def find_version(packages: list[dict], tag_filter: str) -> Tuple[str, str]:
    """Return (digest, created_at_iso) for the version whose tag list contains ``tag_filter``."""
    for v in packages:
        tags = v.get("metadata", {}).get("container", {}).get("tags", [])
        if tag_filter in tags:
            digest = v["name"]
            created = v.get("created_at", "")
            if not digest.startswith("sha256:"):
                raise SystemExit(f"unexpected digest format: {digest}")
            return digest, created
    raise SystemExit(f"no GHCR version found with tag {tag_filter!r}")


def fmt_ts(iso: str) -> str:
    return iso.replace("T", " ").replace("Z", "").split(".")[0]


def main() -> None:
    ext_ver = os.environ["EXT_VER"]
    web_ver = os.environ["WEB_VER"]

    owner = os.environ.get("GITHUB_REPOSITORY_OWNER", "styk-tv")
    ext_pkgs = gh_api(f"/users/{owner}/packages/container/pgck/versions")
    web_pkgs = gh_api(f"/users/{owner}/packages/container/pgck-web/versions")

    ext_amd_d, ext_amd_t = find_version(ext_pkgs, f"{ext_ver}-pg17-amd64")
    ext_arm_d, ext_arm_t = find_version(ext_pkgs, f"{ext_ver}-pg17-arm64")
    web_amd_d, web_amd_t = find_version(web_pkgs, f"{web_ver}-amd64")
    web_arm_d, web_arm_t = find_version(web_pkgs, f"{web_ver}-arm64")

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    out = f"""<!--
  This file is auto-generated by .github/workflows/update-latest-md.yml
  after a successful release.yml / publish-pgck-web.yml run AND after
  SLSA Build Provenance v1 attestations have been verified against the
  GHCR digests below. Do NOT edit by hand — the next workflow run will
  overwrite your changes. Last refresh: {now}.
-->

# pgCK — latest published artifacts

Two publishable surfaces ship from this repo: the PostgreSQL **extension** (oras-pulled OCI artifact) and the **pgck-web** FastAPI runtime (docker image). This file tracks the head of each on **PostgreSQL 17**. Older PG majors (14, 15, 16) are still built per release — see [Repo packages view](https://github.com/styk-tv/pgCK/pkgs/container/pgck) for the full matrix.

## pgCK extension — `v{ext_ver}` (PostgreSQL 17)

`oras pull ghcr.io/styk-tv/pgck:{ext_ver}-pg17-<arch>` → drop `lib/pgck.so` + `share/extension/{{pgck.control, pgck--{ext_ver}.sql}}` next to your `postgres:17` install.

| arch  | Pull URI                                  | Digest                                                                  | Created (UTC)       |
|-------|-------------------------------------------|-------------------------------------------------------------------------|---------------------|
| amd64 | `ghcr.io/styk-tv/pgck:{ext_ver}-pg17-amd64`   | `{ext_amd_d}` | {fmt_ts(ext_amd_t)} |
| arm64 | `ghcr.io/styk-tv/pgck:{ext_ver}-pg17-arm64`   | `{ext_arm_d}` | {fmt_ts(ext_arm_t)} |

|                       |                                                                          |
|-----------------------|--------------------------------------------------------------------------|
| Artifact type         | `application/vnd.styk.pgck.extension.v1`                                 |
| Tarball mirror        | https://github.com/styk-tv/pgCK/releases/tag/v{ext_ver}                  |
| Repo packages view    | https://github.com/styk-tv/pgCK/pkgs/container/pgck                      |
| Older PG majors       | `{ext_ver}-pg{{14,15,16}}-{{amd64,arm64}}` published alongside           |
| Provenance            | SLSA Build Provenance v1 — verify with `gh attestation verify oci://ghcr.io/styk-tv/pgck:{ext_ver}-pg17-amd64 --repo styk-tv/pgCK` |

## pgck-web — `{web_ver}`

FastAPI runtime layer: dual-page Display / Board, `/cklib` mount for the CKClient ESM module (CK.Lib.Js v1.3 aligned), `/assets` mount for static files. Pull and run directly.

| arch  | Pull URI                                  | Also tagged       | Digest                                                                  | Created (UTC)       |
|-------|-------------------------------------------|-------------------|-------------------------------------------------------------------------|---------------------|
| amd64 | `ghcr.io/styk-tv/pgck-web:{web_ver}-amd64`   | `latest-amd64`    | `{web_amd_d}` | {fmt_ts(web_amd_t)} |
| arm64 | `ghcr.io/styk-tv/pgck-web:{web_ver}-arm64`   | `latest-arm64`    | `{web_arm_d}` | {fmt_ts(web_arm_t)} |

|                       |                                                                          |
|-----------------------|--------------------------------------------------------------------------|
| Repo packages view    | https://github.com/styk-tv/pgCK/pkgs/container/pgck-web                  |
| Source                | [`web/`](./web/) (consolidated from `web_demo/` at pgck-web/v0.2.1)      |
| Provenance            | SLSA Build Provenance v1 — verify with `gh attestation verify oci://ghcr.io/styk-tv/pgck-web:{web_ver}-amd64 --repo styk-tv/pgCK` |

## Pin policy

- `latest-amd64` / `latest-arm64` track the **most recent pgck-web tag**. There is no `latest` on the extension OCI artifact — pin by `pg`×`arch` explicitly.
- Tagged versions are immutable on GHCR.
- Every artifact ships with a verifiable **SLSA Build Provenance v1** attestation tying it to a specific GitHub Actions workflow run on this repo. Workstation pushes are not permitted; this file does not advance unless `gh attestation verify` accepts the new digest.

See [`CHANGELOG.md`](./CHANGELOG.md) and [`RELEASE_NOTES.md`](./RELEASE_NOTES.md) for what changed per version.
"""
    sys.stdout.write(out)


if __name__ == "__main__":
    main()
